.TH "DIE-MATCH" "1" "October 2014" "die-match 0.1.10" "User Commands"
.SH "NAME"
die-match
.SH "USAGE"

.SP
die match [\-l] [\-l|\-\-long] [\-p|\-\-pid\-file=<file...>] <args> <ptn...>
.br
die m [\-l] [\-l|\-\-long] [\-p|\-\-pid\-file=<file...>] <args> <ptn...>
.SH "DESCRIPTION"
.PP
Print processes that match patterns.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-l, \-\-long\fR: Include more information (long listing).
.IP "\[ci]" 4
\fB\-p, \-\-pid\-file=[file...]\fR: Read pattern(s) from file(s).
.EL
.SH "BUGS"
.PP
Report bugs to muji noop@xpm.io.
