.TH "DIE-MATCH" "1" "October 2014" "die-match 0.1.5" "User Commands"
.SH "NAME"
die-match
.SH "USAGE"

.SP
die match [\-l] [\-l|\-\-long] <args> <ptn...>
.br
die m [\-l] [\-l|\-\-long] <args> <ptn...>
.SH "DESCRIPTION"
.PP
Print processes that match patterns.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-l, \-\-long\fR: Include more information (long listing).
.EL
.SH "BUGS"
.PP
Report bugs to muji noop@xpm.io.
