.TH "DIE" "1" "October 2014" "die 0.1.1" "User Commands"
.SH "NAME"
die -- Kill groups of processes.
.SH "USAGE"

die <args> <ptn...> \-\- <psargs>
.SH "DESCRIPTION"
.PP
Executes ps(1) and parses the output to an object graph, patterns may then be matched against the graph.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBcolumn, c\fR: Print column names.
.IP "\[ci]" 4
\fBgraph, g\fR: Print parsed object graph.
.IP "\[ci]" 4
\fBmatch, m\fR: Print processes that match <ptn...>.
.IP "\[ci]" 4
\fBkill, k\fR: Kill processes that match <ptn...>.
.IP "\[ci]" 4
\fBhelp\fR: Show help for commands.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-s, \-\-signal=[signal]\fR: Send signal (default TERM).
.IP "\[ci]" 4
\fB\-f, \-\-filter=[name...]\fR: Filter columns, only include <name...>.
.IP "\[ci]" 4
\fB\-c, \-\-cmd\fR: Executable name only in command column. 
.IP "\[ci]" 4
\fB\-\-[no]\-color\fR: Enable or disable terminal colors.
.IP "\[ci]" 4
\fB\-U=[uid]\fR: Display processes for real <uid>.
.IP "\[ci]" 4
\fB\-u=[username]\fR: Display processes for <username>.
.IP "\[ci]" 4
\fB\-\-print\-columns\fR: Print column names.
.IP "\[ci]" 4
\fB\-\-noop\fR: Print matched processes.
.IP "\[ci]" 4
\fB\-\-help\fR: Display this help and exit.
.IP "\[ci]" 4
\fB\-\-version\fR: Print version and exit.
.EL
.SH "USAGE"
.PP
The default arguments passed to ps(1) are \fB\-axf\fR.
.PP
To change the arguments for ps(1) use \fB\-\-\fR followed by the arguments, for example:

.SP
  die c
.br
  die c \-\- \-ax
.PP
Column names are identical to the column titles output by ps(1) except they are converted to lowercase.
.SH "EXAMPLE"
.PP
Print column names:

  die c
.PP
Print parsed ps(1) object graph:

  die g
.PP
Filter the parsed object graph and only show executable name:

  die g \-c pid cmd
.SH "BUGS"
.PP
Report bugs to muji noop@xpm.io.
.SH "SEE ALSO"
.PP
ps(1), kill(1)
